//
// Created by Sea on 2021/9/22.
//

#ifndef EFFECTIVECPP_CLAUSE44_FATOR_PARAM_INDEPENDENT_CODE_OUT_OF_TEMPLATE_HPP
#define EFFECTIVECPP_CLAUSE44_FATOR_PARAM_INDEPENDENT_CODE_OUT_OF_TEMPLATE_HPP


//条款44:将参数无关的代码抽离template











#endif //EFFECTIVECPP_CLAUSE44_FATOR_PARAM_INDEPENDENT_CODE_OUT_OF_TEMPLATE_HPP
