//
// Created by Sea on 2021/9/26.
//

#ifndef EFFECTIVECPP_CLAUSE46_DEFINE_NON_MEMBER_FUNCTION_INSIDE_TEMPLATES_WHEN_TYPE_CONVERSION_ARE_DESIRED_HPP
#define EFFECTIVECPP_CLAUSE46_DEFINE_NON_MEMBER_FUNCTION_INSIDE_TEMPLATES_WHEN_TYPE_CONVERSION_ARE_DESIRED_HPP

//条款46:需要类型转换时请为模板定义非成员函数
//条款24讨论过为什么只有非成员函数(non-memeber)才有能力"再所哟实参身上实施隐式类型转换"。











#endif //EFFECTIVECPP_CLAUSE46_DEFINE_NON_MEMBER_FUNCTION_INSIDE_TEMPLATES_WHEN_TYPE_CONVERSION_ARE_DESIRED_HPP
